import os
from platform import system
import json

developerMode = True

hostsPath = "tests/hosts.txt"
hostsComment = """\n
# Generated by Hippie
# The following is a list of AI sites\n
"""

sitesPath = "assets/sites.json"

def isWindows():
    try:
        if developerMode:
            return True
        else:
            return system().lower() == "windows"
    except not system():
        print("ERROR: System not type not found")

def openSites():
    with open(sitesPath, "r") as f:
        data = json.load(f)

        sites = data.get("sites", [])
        return sites

def commentInFile(file):
    with open(file, "r", encoding="utf-8") as f:
        comment = hostsComment.partition('\n')[0]

        if comment in f:
            return True
        else:
            return False

def writeToHosts():
    sites = openSites()

    with open(hostsPath, "a", encoding="utf-8") as f:
        if not commentInFile(hostsPath): 
            f.write(f"{hostsComment}\n")

        for site in sites:
            name = site.get("name")
            url = site.get("url")

            if not url:
                continue

            f.write(
f"""# {name}
127.0.0.1  \t{url}\n"""
            )
            print(name)

if isWindows():
    writeToHosts()
